# Generated by Django 5.1.15 on 2026-07-16 05:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0004_checklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('kind', models.CharField(choices=[('internal', 'Internal'), ('campaign', 'Campaign'), ('lead', 'Lead'), ('client', 'Client')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='orgs.membership')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payouts', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_payouts', to='orgs.membership')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='projects.project')),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('agreed_on', models.DateField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('ref', models.CharField(max_length=500)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='projects.deal')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_splits', to='orgs.membership')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
            ],
            options={
                'ordering': ['-percent'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('org', 'slug'), name='uniq_project_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='projectlink',
            constraint=models.UniqueConstraint(fields=('project', 'label'), name='uniq_link_project_label'),
        ),
        migrations.AddConstraint(
            model_name='split',
            constraint=models.UniqueConstraint(fields=('deal', 'membership'), name='uniq_split_deal_member'),
        ),
    ]
