# Generated by Django 5.1.15 on 2026-07-20 23:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="Public profile bio, in the person's own words."),
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('website', 'Website'), ('bluesky', 'Bluesky'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('github', 'GitHub'), ('mastodon', 'Mastodon'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('calendar', 'Calendar / booking'), ('resume', 'Resume / CV'), ('other', 'Other')], default='website', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Display label; useful for kind=other or multiple sites.', max_length=100)),
                ('handle', models.CharField(blank=True, help_text="Platform handle, e.g. '@name.bsky.social'. Parseable, no URL.", max_length=255)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False, help_text="Person's opt-in: show this link on their public profile.")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('url__gt', ''), ('handle__gt', ''), _connector='OR'), name='profilelink_url_or_handle')],
            },
        ),
    ]
