# Generated by Django 5.1.15 on 2026-07-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_profilelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
