# Generated by Django 5.1.15 on 2026-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilelink_url_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_url',
            field=models.URLField(blank=True, help_text='Your booking link, if you take meetings (Calendly, Cal.com, Google).', max_length=1000),
        ),
    ]
