# Generated by Django 5.1.15 on 2026-07-27 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0018_remove_org_initial_shares_done_org_pie_locked_at_and_more'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieLockVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pie_lock_votes', to='orgs.org')),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pie_lock', to='votes.vote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
