# Generated by Django 5.1.15 on 2026-08-08 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_slug', models.SlugField(max_length=64)),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('sections', models.JSONField(blank=True, default=list)),
                ('items', models.JSONField(blank=True, default=list)),
                ('previous', models.JSONField(blank=True, null=True)),
                ('tz_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comms_edition',
                'ordering': ['-window_start'],
                'constraints': [models.UniqueConstraint(fields=('org_slug', 'window_start'), name='comms_one_edition_per_week')],
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.SlugField(max_length=40)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('public_token', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='comms.edition')),
            ],
            options={
                'db_table': 'comms_send',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'audience'), name='comms_one_send_per_audience')],
            },
        ),
    ]
