# Generated by Django 5.1.15 on 2026-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_slug', models.SlugField(max_length=64)),
                ('audience', models.SlugField(max_length=40)),
                ('source', models.CharField(max_length=16)),
                ('external_id', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('via', models.CharField(blank=True, max_length=120)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comms_subscriber',
                'ordering': ['name', 'email'],
                'indexes': [models.Index(fields=['org_slug', 'audience', 'email'], name='comms_subsc_org_slu_f4fc23_idx')],
                'constraints': [models.UniqueConstraint(fields=('org_slug', 'audience', 'source', 'external_id'), name='comms_one_row_per_person_per_list')],
            },
        ),
    ]
