# Generated by Django 5.1.15 on 2026-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_send_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='body_html',
            field=models.TextField(blank=True),
        ),
    ]
