# Generated by Django 5.1.15 on 2026-07-06 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("options", models.JSONField(default=list)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("weight_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.org"),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("choice", models.CharField(max_length=255)),
                ("cast_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to="orgs.membership",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.org"),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to="votes.vote",
                    ),
                ),
            ],
            options={
                "ordering": ["vote", "membership"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vote", "membership"), name="uniq_ballot_vote_member"
                    )
                ],
            },
        ),
    ]
