# Generated by Django 5.1.15 on 2026-07-06 03:12

import apps.tasksources.fields
import apps.tasksources.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSourceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "adapter_type",
                    models.CharField(choices=[("taiga", "Taiga")], default="taiga", max_length=32),
                ),
                ("base_url", models.URLField(help_text="Tracker REST API base URL.")),
                (
                    "api_token",
                    apps.tasksources.fields.EncryptedTextField(
                        blank=True, help_text="Encrypted at rest (Fernet)."
                    ),
                ),
                (
                    "project_selector",
                    models.CharField(
                        blank=True,
                        help_text="Which project(s) to pull, e.g. a Taiga project slug or id.",
                        max_length=255,
                    ),
                ),
                (
                    "value_tag_pattern",
                    models.CharField(
                        default="(\\d+)\\s*",
                        help_text="Regex (case-insensitive) matched against task tags in direct_value mode; group 1 is the numeric value. e.g. r'(\\d+)\\s*cook'.",
                        max_length=128,
                    ),
                ),
                (
                    "hours_field",
                    models.CharField(
                        blank=True,
                        help_text="Name of the custom attribute / field carrying hours in hours_rate mode.",
                        max_length=128,
                    ),
                ),
                (
                    "cash_field",
                    models.CharField(
                        blank=True,
                        help_text="Name of the custom attribute / field carrying cash attached to a task.",
                        max_length=128,
                    ),
                ),
                (
                    "done_statuses",
                    models.JSONField(
                        default=apps.tasksources.models.default_done_statuses,
                        help_text="Status slugs that count as done/eligible.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.org"),
                ),
            ],
            options={
                "verbose_name": "task source config",
                "verbose_name_plural": "task source configs",
            },
        ),
        migrations.CreateModel(
            name="TrackedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("external_url", models.URLField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=500)),
                (
                    "claimed_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                (
                    "hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "cash",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=64)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracked_tasks",
                        to="orgs.membership",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.org"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasksources.tasksourceconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at", "external_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "source", "external_id"),
                        name="uniq_task_org_source_external",
                    )
                ],
            },
        ),
    ]
