# Generated by Django 5.1.15 on 2026-07-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksourceconfig',
            name='value_tag_pattern',
            field=models.CharField(blank=True, default='', help_text="Regex (case-insensitive) matched against task tags in direct_value mode; group 1 is the numeric value, e.g. r'(\\d+)\\s*cook'. Leave EMPTY to disable value parsing (tasks then surface as missing-value) — there is deliberately no greedy default, which would miscount any number in any tag.", max_length=128),
        ),
    ]
