# Generated by Django 5.1.15 on 2026-07-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksources', '0002_alter_tasksourceconfig_value_tag_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksourceconfig',
            name='base_url',
            field=models.URLField(help_text='Tracker REST API base URL.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='trackedtask',
            name='external_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
