# Generated by Django 5.1.15 on 2026-08-10 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_ventureinterest'),
        ('orgs', '0025_invitelink_invite_from_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('in_kind', 'In kind')], default='cash', max_length=10)),
                ('tier', models.SlugField(blank=True, max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer', models.TextField(blank=True)),
                ('note', models.TextField(blank=True, help_text='Their own words. Never generated.')),
                ('list_publicly', models.BooleanField(default=True)),
                ('listed_as', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_pledges', to='orgs.org')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_pledges_answered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('responded_at'), nulls_first=True), 'created_at'],
            },
        ),
    ]
