# Generated by Django 5.1.15 on 2026-07-06 03:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        ("tasksources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DropRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("approved", "Approved")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_drop_runs",
                        to="orgs.membership",
                    ),
                ),
                (
                    "opened_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_drop_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.org"),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="DropLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "computed_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=16),
                ),
                (
                    "adjustment",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=16),
                ),
                ("adjustment_reason", models.CharField(blank=True, max_length=500)),
                (
                    "final_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=16),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drop_lines",
                        to="orgs.membership",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.org"),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="drop_lines", to="tasksources.trackedtask"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="drops.droprun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "membership"],
            },
        ),
    ]
