# Generated by Django 5.1.15 on 2026-07-06 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SortitionDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seats", models.PositiveIntegerField()),
                (
                    "weight_window",
                    models.CharField(
                        choices=[("all_time", "All time"), ("trailing_12m", "Trailing 12 months")],
                        default="all_time",
                        max_length=20,
                    ),
                ),
                (
                    "seed",
                    models.CharField(
                        help_text="Deterministic seed; same seed + weights reproduces the draw.",
                        max_length=128,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.org"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
