# Generated by Django 5.1.15 on 2026-07-06 03:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("unit_name", models.CharField(default="points", max_length=32)),
                (
                    "default_hourly_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("steward", "Steward"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides Org.default_hourly_rate for this person. Null = use org default.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("taiga_username", models.CharField(blank=True, max_length=255)),
                ("taiga_user_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "ordering": ["org", "user"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=16)),
                ("source_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="orgs.membership",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValuationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "valuation_mode",
                    models.CharField(
                        choices=[
                            ("hours_rate", "Hours x rate"),
                            ("direct_value", "Direct value tags"),
                        ],
                        default="hours_rate",
                        max_length=20,
                    ),
                ),
                (
                    "at_risk_multiplier_noncash",
                    models.DecimalField(decimal_places=3, default=Decimal("1.0"), max_digits=6),
                ),
                (
                    "at_risk_multiplier_cash",
                    models.DecimalField(decimal_places=3, default=Decimal("1.0"), max_digits=6),
                ),
                (
                    "weight_window",
                    models.CharField(
                        choices=[("all_time", "All time"), ("trailing_12m", "Trailing 12 months")],
                        default="all_time",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_budget_period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_budget_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Assignable value per period. Null = unlimited.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "self_assign_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max value a member may self-assign per period. Null = no cap.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "budget_enforcement",
                    models.CharField(
                        choices=[
                            ("soft", "Soft (warn on exceed)"),
                            ("hard", "Hard (block on exceed)"),
                        ],
                        default="soft",
                        max_length=10,
                    ),
                ),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_config",
                        to="orgs.org",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("org", "user"), name="uniq_membership_org_user"
            ),
        ),
    ]
