# Generated by Django 5.1.15 on 2026-07-13 01:19

import apps.orgs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.orgs.models.new_invite_code, max_length=32, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('steward', 'Steward'), ('member', 'Member')], default='member', max_length=20)),
                ('audience', models.CharField(choices=[('advisor', 'Advisor'), ('mentor', 'Mentor'), ('partner', 'Partner'), ('funder', 'Funder'), ('founder', 'Founder'), ('supporter', 'Supporter')], default='supporter', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('link', models.URLField(blank=True, help_text='Their LinkedIn or website.')),
                ('image_url', models.URLField(blank=True)),
                ('drafted_statement', models.TextField(blank=True)),
                ('drafted_social_post', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('committed', 'Committed'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='created', max_length=20)),
                ('committed_claim_id', models.IntegerField(blank=True, null=True)),
                ('statement_as_published', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField(default=apps.orgs.models.default_invite_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='orgs.org')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
