# Generated by Django 5.1.15 on 2026-07-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='venture_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invite',
            name='venture_url',
            field=models.URLField(blank=True),
        ),
    ]
