# Generated by Django 5.1.15 on 2026-07-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='doorway',
            field=models.BooleanField(default=False),
        ),
    ]
