# Generated by Django 5.1.15 on 2026-07-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_invite_accepted_by_invite_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='audience',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('funder', 'Funder'), ('founder', 'Founder'), ('supporter', 'Supporter')], default='supporter', max_length=20),
        ),
    ]
