# Generated by Django 5.1.15 on 2026-07-22 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# The curriculum as it stood when per-org copies were retired, frozen here on
# purpose: a data migration must not follow later edits to apps.orgs.genesis.
# (module, order) is how seed_genesis wrote rows, so it is how we read them back.
KEYS_AT_MIGRATION = {
    ("exist", 0): "exist.prior-art",
    ("exist", 1): "exist.paragraph",
    ("exist", 2): "exist.who-else",
    ("who", 0): "who.three-people",
    ("who", 1): "who.talk-to-one",
    ("build", 0): "build.smallest",
    ("build", 1): "build.in-front-of-user",
    ("money", 0): "money.one-page",
    ("money", 1): "money.first-yes",
    ("receipts", 0): "receipts.connect-tracker",
    ("receipts", 1): "receipts.first-drop",
    ("receipts", 2): "receipts.trace-a-slice",
}


def forwards(apps, schema_editor):
    """
    Per-org checklist copies become events.

    An org that had rows was on the path, so it gets genesis_started_at (its
    creation date, the closest honest answer). Every done item becomes one tick
    carrying its original timestamp, actor, and wording. Unticked items produce
    nothing: not having done something is the absence of an event, not an event.
    """
    ChecklistItem = apps.get_model("orgs", "ChecklistItem")
    ChecklistEvent = apps.get_model("orgs", "ChecklistEvent")
    Org = apps.get_model("orgs", "Org")

    org_ids = set(ChecklistItem.objects.values_list("org_id", flat=True))
    for org in Org.objects.filter(id__in=org_ids):
        Org.objects.filter(id=org.id, genesis_started_at__isnull=True).update(
            genesis_started_at=org.created_at
        )

    events = []
    for item in ChecklistItem.objects.filter(done_at__isnull=False).order_by("id"):
        key = KEYS_AT_MIGRATION.get((item.module, item.order))
        if key is None:
            # An item this deployment added or reordered by hand. Keep the record
            # rather than drop it; it renders as retired, titled as it read.
            key = f"{item.module}.legacy-{item.order}"
        events.append(
            ChecklistEvent(
                org_id=item.org_id,
                item_key=key[:64],
                action="tick",
                actor_id=item.done_by_id,
                at=item.done_at,
                title_shown=item.title[:255],
            )
        )
    ChecklistEvent.objects.bulk_create(events)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_invite_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='genesis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChecklistEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('tick', 'Ticked'), ('untick', 'Unticked')], max_length=10)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title_shown', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_events', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_events', to='orgs.org')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.AddIndex(
            model_name='checklistevent',
            index=models.Index(fields=['org', 'item_key', 'at'], name='orgs_checkl_org_id_c9a2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistevent',
            index=models.Index(fields=['org', 'at'], name='orgs_checkl_org_id_df2871_idx'),
        ),
    ]
