# Generated by Django 5.1.15 on 2026-07-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_checklist_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accelerator_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts_run', to='orgs.org')),
            ],
            options={
                'ordering': ['-starts_on', 'name'],
            },
        ),
        migrations.AddField(
            model_name='org',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='orgs.cohort'),
        ),
    ]
