# Generated by Django 5.1.15 on 2026-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='kind',
            field=models.CharField(choices=[('org', 'Org membership'), ('pool', 'Applicant pool'), ('byov', 'BYOV: Founder bringing their own venture')], default='org', max_length=10),
        ),
    ]
