# Generated by Django 5.1.15 on 2026-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_alter_invite_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='repos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='org',
            name='socials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='org',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
