# Generated by Django 5.1.15 on 2026-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_org_repos_org_socials_org_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='calendar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='org',
            name='chat_url',
            field=models.URLField(blank=True),
        ),
    ]
