# Generated by Django 5.1.15 on 2026-07-25 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Sponsor equity: an outside company (ExternalHolder — LinkedTrust, whose own cap
    table lives on Fairmint, not here) can hold a stake in a venture org, and a BYOV
    invite can carry the founding split that seeds one at accept.

    Purely additive. Every new column is nullable with no default, no existing row
    changes, and no existing pie moves: an org with no OrgStake rows and invites with a
    blank sponsor computes exactly as it did before.
    """

    dependencies = [
        ('orgs', '0012_org_calendar_url_org_chat_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text="Where this company's own equity actually lives, e.g. its Fairmint cap table. A reference for people to follow. GovKit never reads or computes it.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='invite',
            name='founding_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="BYOV: the venture's total pie at genesis, in its own units.", max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='sponsor_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='BYOV: percent of the founding value the sponsor keeps, 0-100.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='default_founding_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prefills the starting value of a sponsored venture's pie. Blank = no default.", max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='default_sponsor_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prefills the share of a sponsored venture this org keeps, 0-100. Blank = no default.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='BYOV: the outside company taking a share of this venture.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invites_sponsored', to='orgs.externalholder'),
        ),
        migrations.AddField(
            model_name='org',
            name='default_sponsor',
            field=models.ForeignKey(blank=True, help_text='Prefills who takes the sponsor share on a BYOV invite from this org.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_defaulting_to', to='orgs.externalholder'),
        ),
        migrations.CreateModel(
            name='OrgStake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('source_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_stakes_granted', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakes', to='orgs.externalholder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_stakes', to='orgs.org')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
