# Generated by Django 5.1.15 on 2026-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_external_holders_and_founding_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='pie_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='pie_url',
            field=models.URLField(blank=True),
        ),
    ]
