# Generated by Django 5.1.15 on 2026-07-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_org_pie_as_of_org_pie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='pitch',
            field=models.TextField(blank=True, help_text="The team's own words. Never generated."),
        ),
    ]
