# Generated by Django 5.1.15 on 2026-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_org_pitch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='founding_value',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='sponsor_pct',
        ),
        migrations.RemoveField(
            model_name='org',
            name='default_founding_value',
        ),
        migrations.RemoveField(
            model_name='org',
            name='default_sponsor',
        ),
        migrations.RemoveField(
            model_name='org',
            name='default_sponsor_pct',
        ),
        migrations.AddField(
            model_name='org',
            name='initial_shares_done',
            field=models.BooleanField(default=False),
        ),
    ]
