# Generated by Django 5.1.15 on 2026-07-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_remove_invite_founding_value_remove_invite_sponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
