# Generated by Django 5.1.15 on 2026-07-27 00:04
#
# initial_shares_done becomes pie_phase. An org that had ticked "done" had finished
# recording its start and was earning on top, which is exactly LAUNCHED (nothing was
# ever voted, so nothing maps to LOCKED). Everyone else stays in SETUP.

from django.conf import settings
from django.db import migrations, models


def _done_to_launched(apps, schema_editor):
    Org = apps.get_model("orgs", "Org")
    Org.objects.filter(initial_shares_done=True).update(pie_phase="launched")


def _launched_to_done(apps, schema_editor):
    Org = apps.get_model("orgs", "Org")
    Org.objects.filter(pie_phase__in=["launched", "locked"]).update(initial_shares_done=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_invite_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='pie_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='pie_phase',
            field=models.CharField(choices=[('setup', 'Setting up'), ('launched', 'Launched'), ('locked', 'Locked in')], default='setup', max_length=12),
        ),
        migrations.RunPython(_done_to_launched, _launched_to_done),
        migrations.RemoveField(
            model_name='org',
            name='initial_shares_done',
        ),
        migrations.AddField(
            model_name='orgstake',
            name='target_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='orgstake',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='orgstake',
            constraint=models.CheckConstraint(condition=models.Q(('value__isnull', False), ('target_pct__isnull', False), _connector='OR'), name='orgstake_value_or_pct'),
        ),
    ]
