# Generated by Django 5.1.15 on 2026-07-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_remove_org_initial_shares_done_org_pie_locked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalholder',
            name='url',
            field=models.URLField(blank=True, help_text="Where this company's own equity actually lives, e.g. its Fairmint cap table. A reference for people to follow. GovKit never reads or computes it.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='invite',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='invite',
            name='link',
            field=models.URLField(blank=True, help_text='Their LinkedIn or website.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='invite',
            name='venture_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='invite',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='org',
            name='calendar_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='org',
            name='chat_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='org',
            name='pie_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='org',
            name='website',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
