# Generated by Django 5.1.15 on 2026-07-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_alter_externalholder_url_alter_invite_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='org',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='org',
            name='looking_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='org',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
