# Generated by Django 5.1.15 on 2026-07-28 16:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_org_cover_image_url_org_logo_url_org_looking_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationconfig',
            name='default_task_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.00'), help_text='Hours credited for a done task that carries none. Null = credit nothing.', max_digits=8, null=True),
        ),
    ]
