# Generated by Django 5.1.15 on 2026-07-28 19:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_valuationconfig_default_task_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='calendar_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrgLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='orgs.org')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('thumb_url', models.URLField(blank=True, max_length=1000)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='orgs.org')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_on', models.DateField(default=datetime.date.today)),
                ('words', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('thumb_url', models.URLField(blank=True, max_length=1000)),
                ('link_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='orgs.org')),
            ],
            options={
                'ordering': ['-happened_on', '-id'],
            },
        ),
    ]
