# Generated by Django 5.1.15 on 2026-07-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_org_calendar_public_orglink_orgpicture_orgpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('said_by', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('said_on', models.DateField(blank=True, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='orgs.org')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
