# Generated by Django 5.1.15 on 2026-08-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_orgquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='discord_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='membership',
            name='discord_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
