# Generated by Django 5.1.15 on 2026-08-05 14:44

import apps.orgs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_membership_discord_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.orgs.models.new_invite_code, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('org', 'Org membership'), ('pool', 'Applicant pool'), ('byov', 'BYOV: Founder bringing their own venture')], default='pool', max_length=10)),
                ('audience', models.CharField(choices=[('mentor', 'Mentor'), ('funder', 'Funder'), ('founder', 'Founder'), ('supporter', 'Supporter')], default='founder', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('steward', 'Steward'), ('member', 'Member')], default='member', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Blank means no limit.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Blank means no expiry.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_links_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='orgs.org')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invite',
            name='from_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='orgs.invitelink'),
        ),
    ]
