# Generated by Django 5.1.15 on 2026-08-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_checklisttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgstake',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
    ]
